from aiogram.fsm.state import StatesGroup, State
class CreateBot(StatesGroup): kind=State(); token=State()
class GlobalSetting(StatesGroup): create_price=State(); referral_bonus=State()
class ChangeBotToken(StatesGroup): token=State()
class AddMovie(StatesGroup): code=State(); action=State(); title=State(); premium=State(); media=State()
class DelMovie(StatesGroup): code=State()
class EditMovie(StatesGroup): code=State(); action=State(); value=State()
class AddChannel(StatesGroup): kind=State(); title=State(); chat=State(); url=State()
class DelChannel(StatesGroup): id=State()
class AddAdmin(StatesGroup): user_id=State()
class DelAdmin(StatesGroup): user_id=State()
class AddTariff(StatesGroup): name=State(); days=State(); price=State()
class EditTariff(StatesGroup): tariff_id=State(); field=State(); value=State()
class GrantPremium(StatesGroup): user_id=State(); days=State()
class RemovePremium(StatesGroup): user_id=State()
class AddPay(StatesGroup): name=State(); value=State()
class AddAd(StatesGroup): media=State(); buttons=State(); schedule=State(); confirm=State()
class Broadcast(StatesGroup): text=State(); confirm=State()
class BuyPremium(StatesGroup): screenshot=State()
class SetText(StatesGroup): key=State(); value=State()
class SearchMovie(StatesGroup): query=State()
class RequestMovie(StatesGroup): text=State()
class AntiSpamSettings(StatesGroup): limit=State(); window=State(); block=State()

class ReferralSetting(StatesGroup): bonus=State()
class DelPay(StatesGroup): id=State()
class DelTariff(StatesGroup): id=State()

class MainTariffAdmin(StatesGroup): name=State(); monthly_price=State(); daily_limit=State(); speed=State(); edit_id=State(); edit_field=State(); edit_value=State(); delete_id=State()
