from aiogram.fsm.state import StatesGroup, State
class CreateBot(StatesGroup): kind=State(); token=State()
class GlobalSetting(StatesGroup): create_price=State(); referral_bonus=State()
class ChangeBotToken(StatesGroup): token=State()
class AddMovie(StatesGroup): code=State(); action=State(); title=State(); premium=State(); media=State()
class DelMovie(StatesGroup): code=State()
class EditMovie(StatesGroup): code=State()
class AddChannel(StatesGroup): title=State(); chat=State(); url=State()
class DelChannel(StatesGroup): id=State()
class AddAdmin(StatesGroup): user_id=State()
class DelAdmin(StatesGroup): user_id=State()
class AddTariff(StatesGroup): name=State(); days=State(); price=State()
class GrantPremium(StatesGroup): user_id=State(); days=State()
class RemovePremium(StatesGroup): user_id=State()
class AddPay(StatesGroup): name=State(); value=State()
class AddAd(StatesGroup): title=State(); text=State(); schedule=State()
class Broadcast(StatesGroup): text=State(); confirm=State()
class BuyPremium(StatesGroup): screenshot=State()
class SetText(StatesGroup): key=State(); value=State()
class SearchMovie(StatesGroup): query=State()
class RequestMovie(StatesGroup): text=State()
class AntiSpamSettings(StatesGroup): limit=State(); window=State(); block=State()
